### ISSUE TITLE
IndexOutOfBounds in MusicPlayer

### ISSUE THREAD

**Issue by lucaspape** [lucaspape/catplayer#54]
```
java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.get (ArrayList.java:437)
  at de.lucaspape.monstercat.core.music.MusicPlayerKt.getNextSongId (MusicPlayer.kt:428)
  at de.lucaspape.monstercat.core.music.util.PlaybackUtilKt$runSeekBarUpdate$updateSeekBar$1.run (PlaybackUtil.kt:215)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7124)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
```

**Comment by lucaspape** [comment]
Should be fixed with https://github.com/lucaspape/catplayer/commit/ce5f1365682877d3ed3e1ae4a4bba63a55cab986

**Comment by lucaspape** [comment]
```
java.lang.IndexOutOfBoundsException: Index: 18, Size: 18
	at java.util.ArrayList.get(ArrayList.java:437)
	at de.lucaspape.monstercat.core.music.MusicPlayerKt.nextSong(MusicPlayer.kt:346)
	at de.lucaspape.monstercat.core.music.MusicPlayerKt.next(MusicPlayer.kt:160)
	at de.lucaspape.monstercat.ui.pages.FullscreenPlayerPage$registerListeners$2.onClick(FullscreenPlayerPage.kt:160)
	at android.view.View.performClick(View.java:7184)
	at android.view.View.performClickInternal(View.java:7161)
	at android.view.View.access$3500(View.java:818)
	at android.view.View$PerformClick.run(View.java:27683)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

Still happening, reproduce: enable shuffle and then quickly skip thru songs

**Comment by lucaspape** [comment]
Should be fixed now in https://github.com/lucaspape/catplayer/commit/bf1448afcfb9cdbb07367e81959afae5e06a189e, it was probably caused by

```
//prepare nextRandom
if (songQueue.size > 0) {
     nextRelatedRandom = Random.nextInt(relatedSongQueue.size)
}
```

which always should have been:  

```
//prepare nextRandom
if (relatedSongQueue.size > 0) {
     nextRelatedRandom = Random.nextInt(relatedSongQueue.size)
}
```
