### ISSUE TITLE
Crash when removing last song from queue view 

### ISSUE THREAD

**Issue by lucaspape** [lucaspape/catplayer#61]

**Comment by lucaspape** [comment]
```java.lang.IndexOutOfBoundsException: Index: 44, Size: 44
	at java.util.ArrayList.get(ArrayList.java:437)
	at de.lucaspape.monstercat.ui.pages.recycler.QueueRecyclerPage.onMenuButtonClick(QueueRecyclerPage.kt:51)
	at de.lucaspape.monstercat.ui.pages.util.RecyclerViewPage$setupRecyclerView$2$3$onClick$1.invokeSuspend(RecyclerViewPage.kt:212)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)```

**Comment by lucaspape** [comment]
Workaround https://github.com/lucaspape/catplayer/commit/39c0dbb02587d19285df81650ab1d5cb85d274ff should fix this
