### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by lucaspape** [lucaspape/catplayer#62]
```

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at de.lucaspape.monstercat.ui.pages.recycler.QueueRecyclerPage.load(QueueRecyclerPage.kt:100)
	at de.lucaspape.monstercat.ui.pages.util.RecyclerViewPage.loadInit(RecyclerViewPage.kt:301)
	at de.lucaspape.monstercat.ui.pages.util.RecyclerViewPage$reload$1.invokeSuspend(RecyclerViewPage.kt:118)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

Not sure how I caused this

**Comment by lucaspape** [comment]
https://github.com/lucaspape/catplayer/commit/c471de9a37108e3438368f05970bc9685a0f544a should hopefully fix this
