### ISSUE TITLE
App crash on start on some devices caused by drawables with variable color

### ISSUE THREAD

**Issue by lucaspape** [lucaspape/catplayer#9]
```
FATAL EXCEPTION: main
Process: de.lucaspape.monstercat, PID: 17303
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.lucaspape.monstercat/de.lucaspape.monstercat.activities.MainActivity}: android.view.InflateException: Binary XML file line #51: Binary XML file line #51: Error inflating class ImageButton
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1357)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: android.view.InflateException: Binary XML file line #51: Binary XML file line #51: Error inflating class ImageButton
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at c.b.k.l.b()
	at c.b.k.i.setContentView()
	at de.lucaspape.monstercat.activities.MainActivity.onCreate(:7)
	at android.app.Activity.performCreate(Activity.java:6259)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2382)
	... 9 more
Caused by: android.view.InflateException: Binary XML file line #51: Error inflating class ImageButton
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 17 more
Caused by: android.content.res.Resources$NotFoundException: Resource "de.lucaspape.monstercat:drawable/ic_play_arrow_24dp" (7f0700a4) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f0700a4 a=-1 r=0x7f0700a4}
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2605)
	at android.content.res.Resources.loadDrawable(Resources.java:2543)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
	at android.widget.ImageView.<init>(ImageView.java:162)
	at android.widget.ImageButton.<init>(ImageButton.java:84)
	at android.widget.ImageButton.<init>(ImageButton.java:80)
	at c.b.p.l.<init>()
	at c.b.p.l.<init>()
	at androidx.appcompat.app.AppCompatViewInflater.createImageButton()
	at androidx.appcompat.app.AppCompatViewInflater.createView()
	at c.b.k.l.onCreateView(:3)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
	... 21 more
```

**Comment by lucaspape** [comment]
Android 6.0 issue
